# Generated by Django 2.2.16 on 2022-11-27 09:49

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[accounts.validators.PhoneNumberValidator]),
        ),
    ]
