# Generated by Django 3.2 on 2022-10-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
