# Generated by Django 3.2 on 2022-10-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20221003_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
